version: '3.8'
services:
  movieapp-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=movieapp
    volumes:
      - movieapp:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  movieapp: