GET http://localhost:8080/movies
Accept: application/json

###
GET http://localhost:8080/movies/5
Accept: application/json

###
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "movie 4",
  "movieDetails": {
    "desc": "brief desc",
    "duration": 121,
    "release_date": "2004-12-12",
    "rating": 12.563
  }
}

###
PUT http://localhost:8080/movies/1
Content-Type: application/json

{
  "title": "movie 1111",
  "movieDetails": {
    "desc": "brief desc",
    "duration": 121,
    "release_date": "2004-12-12",
    "rating": 1112.563
  }
}

###
DELETE http://localhost:8080/movies/1

###






POST http://localhost:8080/movies/5/review
Content-Type: application/json

{
  "reviewer": "Zaid",
  "feedback": "boring",
  "rating": 1
}


###
GET http://localhost:8080/movies/4/reviews
Accept: application/json

###
GET http://localhost:8080/reviews/7
Accept: application/json

###