GET http://localhost:3000/movies
Accept: application/json

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "movie 4",
  "details": {
    "desc": "brief desc",
    "duration": 121,
    "release_date": "2004-12-12",
    "rating": 12.563
  }
}

###




