CREATE TABLE genre (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255)
);

CREATE TABLE movie_genre (
                             movie_id BIGINT,
                             genre_id BIGINT,
                             PRIMARY KEY (movie_id, genre_id),
                             FOREIGN KEY (movie_id) REFERENCES movie (id),
                             FOREIGN KEY (genre_id) REFERENCES genre (id)
);