CREATE TABLE review (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        reviewer VARCHAR(255),
                        reviewDesc VARCHAR(255),
                        rating BIGINT,
                        movie_id BIGINT,
                        FOREIGN KEY (movie_id) REFERENCES movie (id)
);